/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TabItem,
} from './beans/index.js';


export namespace Components {
  interface FooterIpad {}
  interface ZaniTab {
    'tabProps': TabItem;
  }
}

declare global {


  interface HTMLFooterIpadElement extends Components.FooterIpad, HTMLStencilElement {}
  var HTMLFooterIpadElement: {
    prototype: HTMLFooterIpadElement;
    new (): HTMLFooterIpadElement;
  };

  interface HTMLZaniTabElement extends Components.ZaniTab, HTMLStencilElement {}
  var HTMLZaniTabElement: {
    prototype: HTMLZaniTabElement;
    new (): HTMLZaniTabElement;
  };
  interface HTMLElementTagNameMap {
    'footer-ipad': HTMLFooterIpadElement;
    'zani-tab': HTMLZaniTabElement;
  }
}

declare namespace LocalJSX {
  interface FooterIpad extends JSXBase.HTMLAttributes<HTMLFooterIpadElement> {}
  interface ZaniTab extends JSXBase.HTMLAttributes<HTMLZaniTabElement> {
    'tabProps'?: TabItem;
  }

  interface IntrinsicElements {
    'footer-ipad': FooterIpad;
    'zani-tab': ZaniTab;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


