/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FooterIpad {}
  interface TabWrapper {
    'myProp': string;
  }
  interface ZaniTab {
    'someFunc': Function;
    'tabname': string;
  }
}

declare global {


  interface HTMLFooterIpadElement extends Components.FooterIpad, HTMLStencilElement {}
  var HTMLFooterIpadElement: {
    prototype: HTMLFooterIpadElement;
    new (): HTMLFooterIpadElement;
  };

  interface HTMLTabWrapperElement extends Components.TabWrapper, HTMLStencilElement {}
  var HTMLTabWrapperElement: {
    prototype: HTMLTabWrapperElement;
    new (): HTMLTabWrapperElement;
  };

  interface HTMLZaniTabElement extends Components.ZaniTab, HTMLStencilElement {}
  var HTMLZaniTabElement: {
    prototype: HTMLZaniTabElement;
    new (): HTMLZaniTabElement;
  };
  interface HTMLElementTagNameMap {
    'footer-ipad': HTMLFooterIpadElement;
    'tab-wrapper': HTMLTabWrapperElement;
    'zani-tab': HTMLZaniTabElement;
  }
}

declare namespace LocalJSX {
  interface FooterIpad extends JSXBase.HTMLAttributes<HTMLFooterIpadElement> {}
  interface TabWrapper extends JSXBase.HTMLAttributes<HTMLTabWrapperElement> {
    'myProp'?: string;
  }
  interface ZaniTab extends JSXBase.HTMLAttributes<HTMLZaniTabElement> {
    'someFunc'?: Function;
    'tabname'?: string;
  }

  interface IntrinsicElements {
    'footer-ipad': FooterIpad;
    'tab-wrapper': TabWrapper;
    'zani-tab': ZaniTab;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


